WebAccess 1.0
idlesign/pythonz pull request #86
Opened 2021-11-27 18:06 UTC by gaponsasha

Проведен автоматический анализ доступности платформы с помощью инструмента WAVE.
Был выявлен ряд проблем. Ниже перечислю исправленные

1.Кнопка выпадающего меню не имеет описания, что может быть проблемой для программ экранного доступа 
-- добавила title
2. Для основного меню (вверху экрана) контрастность фона и текста корректна только для AA с шрифтом >18pt 
3. -- nav-link предполагает такой цвет текста
-- сделала style="color: #4f4f4f;" для всех элементов меню в неактивном состоянии и полужирный шрифт в активном.
3. Для всего меню (сверху) bootstrap для обеспечения доступности позволяет использовать атрибутов "role=navigation", тогда при озвучке экранный диктор будет сообщать, что это навигационный блок -- добавила.
4. Для пути к веб-странице (указан через "/" в верхней части body страницы) можно указать, что это также элемент навигации: "Since breadcrumbs provide a navigation, it’s a good idea to add a meaningful label such as aria-label="breadcrumb" to describe the type of navigation provided in the <nav> element"
-- добавила его.
5. Для пути к веб-странице у названия финальной страницы в пути слишком низкий контраст с фоном -- поменяла контрастность у этого элемента
6. Поменяла цвет для RSS, чтобы соответствовал требованиям контрастности
7. Переход по страницам -- проблематично менять цвета (для них недостаточная контрастность), добавила title для всех кнопок (переходы будут корректней озвучиваться программами экранного доступа)

2021-11-29 02:04 UTC, idlesign requested changes

2021-11-29 02:04 UTC, idlesign commented on pythonz/apps/templates/sub/static_base.html
> +    function yaAd(renderDetails){
Это похоже на возвращение старого кода.
Вероятно твоя версия кода была ответвлена от источника до того, как я скорректировал вызовы (https://github.com/idlesign/pythonz/commit/8d34b8551afb78f0d50a780ede989f5cc1ef2c2a#diff-7e536a5d364dc9b5792de18fd45f1432b5c25cf2bb9300f9c70f8925fda3875a).

Поэтому эту часть нужно убрать из изменений.

На заметку. Вообще перед отправкой изменений из своей ветки наружу, лучше актуализировать код (подтянуть в свою ветку то новое, что могло появиться за время внесения изменений). Это можно сделать, например, командой `git rebase`.

2022-01-19 17:09 UTC, gaponsasha commented
В новом коммите:
1. Добавила "important" на все style решения, чтоб не было проблем.

Для соблюдения требований контрастности:
2. Затемнила ссылки для навигационного меню перехода по страницам (без проблем уберу, но хотя бы посмотреть, как это выглядит, стоит).
3. Затемнила цвет фона для лайков (был зеленый).
4. Затемнила цвет фона для работы + для актуальности версий (был голубой)
5. Затемнила серый цвет для обсуждений(дат для них)+для синономов поиска в справочнике (cl__grey).
6. Затемнила цвет ссылки в таблице pep, чтобы проходил контрастность.
7. Затемнила цвет для обобщающих слов в путеводителе.

8 Убрала избыточность в карточках (для названий: статей, сообществ, версий, приложений событий, книг, видео, пользователей) -- теперь title добавляется, только если название статьи не отображается полностью.
9. Теперь лайки отображаются, только если их больше 0.
10.  Добавила title для лайков -- чтоб было понятно, что они значат.

2022-01-20 05:37 UTC, idlesign commented
С изменённым bootstrap.css проблема не решена: его не должно быть в этом запросе на изменение.
Может поменяться pythonz.css, но не bootstrap.css.

2022-01-22 02:49 UTC, idlesign requested changes

2022-01-22 02:49 UTC, idlesign commented on pythonz/apps/templates/sitetree/crumbs.html
> +<nav aria-label="breadcrumb" class="breadcrumbs small" aria-label="breadcrumb">
aria-label="breadcrumb" повторяется дважды. Второй раз избыточен.

2022-01-22 02:49 UTC, idlesign commented on pythonz/apps/templates/sub/paginator.html
> +                {% for p in paginator.before_current %}<li><a class="page-link" href="?p={{ p }}" title="Перейти на страницу {{ p }}">{{ p }}</a></li>{% endfor %}
Можно сэкономить на размере html и убрать слово «Перейти»

2022-01-24 01:35 UTC, merged

2022-01-24 01:36 UTC, idlesign commented
Влито. 
Спасибо за участие в проекте!