Feature docker
idlesign/pythonz pull request #87
Opened 2021-12-13 18:50 UTC by lectricas

added feature to create docker containers

2021-12-14 01:35 UTC, idlesign requested changes

2021-12-14 01:35 UTC, idlesign commented on .env.dev
> +DEBUG=1
А что даст этот файл, у нас ведь есть файл конфигурации для разработки (https://github.com/idlesign/pythonz/blob/master/pythonz/settings/env_development.py)?

2021-12-14 01:35 UTC, idlesign commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
А почему нам важны эти две переменные?

2021-12-14 01:35 UTC, idlesign commented on Dockerfile
> +#usage
Лучше прямо в ридми на русском добавить пару строчек, о том, как желающие могут стартовать докер.

2021-12-14 01:35 UTC, idlesign commented on requirements.txt
> +# write here only in English, or docker will refuse to fire up
А что конкретно тебе пишет докер?

2021-12-14 01:35 UTC, idlesign commented on requirements.txt
> -psycopg2==2.9.1
Это нужно вернуть — файл зависимостей описывает их в том числе для боевого окружения.

2021-12-30 14:06 UTC, lectricas commented
Запушил изменения. 

# Environment type: development
Operations to perform:
  Apply all migrations: admin, apps, auth, contenttypes, robots, sessions, siteblocks, sitecats, siteflags, sitegate, sitemessage, sitemetrics, siteprefs, sites, sitetree
Running migrations:
  No migrations to apply.
  Your models in app(s): 'admin', 'apps', 'sitegate' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
# Environment type: development
Superuser created successfully.
Removing intermediate container 7fb2019ef4ef
 ---> 4493deb61f7f
Successfully built 4493deb61f7f
Successfully tagged pythonz_web:latest



Пользователь создается, но залогинится я туда не могу. Юзера в базе данных нет в контейнере нет.

2022-01-10 01:58 UTC, idlesign requested changes

2022-01-10 01:58 UTC, idlesign commented on .env.dev
> +DJANGO_SUPERUSER_USERNAME=admin
В файл такое помещать не нужно, лучше прописать переменные среды в докерфайле вместе с командой createsuperuser

2022-01-10 01:58 UTC, idlesign commented on Dockerfile
> +RUN /bootstrap_docker.sh
Если мы не используем существующий sh файл, то смысла создавать такой же особого нет, с тем же успехом можно все команды  прямо сюда внести, чтобы не плодить сущности сверх потребностей.

2022-01-10 01:58 UTC, idlesign commented on requirements.txt
> +#dataclasses==0.7  # only for python < 3.8
А тут зачем перевод?

2022-01-19 09:29 UTC, lectricas commented on .env.dev
> +DJANGO_SUPERUSER_USERNAME=admin
https://docs.djangoproject.com/en/4.0/ref/django-admin/#createsuperuser
нельзя передавать пароль, его можно только через env

2022-01-19 09:36 UTC, lectricas commented on Dockerfile
> +RUN /bootstrap_docker.sh
done

2022-01-19 09:38 UTC, lectricas commented on requirements.txt
> +#dataclasses==0.7  # only for python < 3.8
done

2022-01-20 05:29 UTC, idlesign requested changes

2022-01-20 05:29 UTC, idlesign commented on .env.dev
> +DJANGO_SUPERUSER_USERNAME=admin
Переменные окружения можно прописать в докерфайле.
А данный файл трогать нет нужды.

2022-01-20 05:29 UTC, idlesign commented on Dockerfile
> +#RUN mkdir state
Зачем тут оставлен комментарий? Если код не требуется, лучше его сразу удалить.

2022-01-20 05:29 UTC, idlesign commented on Dockerfile
> +    pip3 install -r tests/requirements.txt && \
А зачем нам тестовые библиотеки в докере?

2022-01-20 14:18 UTC, lectricas commented on Dockerfile
> +#RUN mkdir state
done

2022-01-20 14:18 UTC, lectricas commented on Dockerfile
> +    pip3 install -r tests/requirements.txt && \
done

2022-01-20 14:19 UTC, lectricas commented
креды теперь лежат в Dockerfile

2022-01-21 01:17 UTC, merged

2022-01-21 01:17 UTC, idlesign commented
Влито. 
Мои поздравления и спасибо за выполненную работу!